services:
  nginx:
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
    restart: always
    volumes:
      - ./nginx/conf:/etc/nginx/conf.d:ro
      - ./certbot/www:/var/www/certbot:ro
      - ./certbot/conf:/etc/letsencrypt:ro

  geoserver:
    build:
      context: .
      args:
        - GS_VERSION=2.26.2
        - CORS_ENABLED=true
        - CORS_ALLOWED_METHODS=GET,POST,PUT,HEAD,OPTIONS
    restart: always
    environment:
      - EXTRA_JAVA_OPTS=-Xms1g -Xmx7g -XX:+UseG1GC
      - INSTALL_EXTENSIONS=true
      - STABLE_EXTENSIONS=gdal
      - COMMUNITY_PLUGIN_URL=https://build.geoserver.org/geoserver/2.26.x/community-latest/geoserver-2.26-SNAPSHOT
      - COMMUNITY_EXTENSIONS=cog-azure,cog-http
      - CORS_ENABLED=true
      - CORS_ALLOWED_ORIGINS=*
      - CORS_ALLOWED_HEADERS=*
      - CORS_ALLOWED_METHODS=GET,POST,PUT,HEAD,OPTIONS
      - GEOSERVER_CSRF_WHITELIST=regiox.no
      - PROXY_BASE_URL=https://gs.regiox.no/geoserver
    volumes:
      - ./geoserver_data:/opt/geoserver_data/:Z
      - ./additional_libs:/opt/additional_libs:Z
    healthcheck:
      test: curl --fail "http://localhost:8080/geoserver/web/wicket/resource/org.geoserver.web.GeoServerBasePage/img/logo.png" || exit 1
      interval: 1m
      retries: 3
      timeout: 20s

  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
