# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - geoserver

on:
  push:
    branches:
      - staging
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to container registry
        uses: docker/login-action@v2
        with:
          registry: https://regiox.azurecr.io/
          username: ${{ secrets.AzureAppService_ContainerUsername_c38677abb1ed4c99854399358e8c2ebd }}
          password: ${{ secrets.AzureAppService_ContainerPassword_e0c902545e8a45fba6474ec571274211 }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: regiox.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_c38677abb1ed4c99854399358e8c2ebd }}/regiox/rx/geoserver-docker:${{ github.sha }}
          file: ./Dockerfile

    deploy:
      runs-on: ubuntu-latest
      needs: build
      environment:
        name: "staging"
        url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

      steps:
        - name: Deploy to Azure Web App
          id: deploy-to-webapp
          uses: azure/webapps-deploy@v2
          with:
            app-name: "geoserver"
            slot-name: "staging"
            publish-profile: ${{ secrets.AzureAppService_PublishProfile_34d54cb30d844cfd928c12cf470f4685 }}
            images: "regiox.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_c38677abb1ed4c99854399358e8c2ebd }}/regiox/rx/geoserver-docker:${{ github.sha }}"
